name: gos-use-case
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pip=21.2.4
  - python=3.9
  - snakemake-minimal=7.5.0
  - pip:
    - setuptools==57.0.0 # needed for pyvcf to compile
    - clodius==0.18.1
    - h5py==3.6.0
    - pyvcf==0.6.8
    - rich==12.3.0
    - gosling[all]==0.0.8
